export const SET_USER_ACCESS = 'SET_USER_ACCESS';
export const SIGNUP = 'SIGNUP';
export const LOGIN = 'LOGIN';
export const MEMBER = 'MEMBER';

export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const ROUTE_HOME = 'ROUTE_HOME';
export const ROUTE_GAME = 'ROUTE_GAME';
export const ROUTE_PROFILE = 'ROUTE_PROFILE';

export const REQUEST_USER_PENDING = 'REQUEST_USER_PENDING';
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS';
export const REQUEST_USER_FAILED = 'REQUEST_USER_FAILED';
export const LOGOUT_USER	= 'LOGOUT_USER';

export const SET_NAME = 'SET_NAME';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_POTION = 'SET_POTION';
export const SET_POTION_NUMBER = 'SET_POTION_NUMBER';
export const SET_USERNAME_EMAIL = 'SET_USERNAME_EMAIL';

export const DEACTIVATE_PENDING = 'DEACTIVATE_PENDING';
export const DEACTIVATE_SUCCESS = 'DEACTIVATE_SUCCESS';
export const DEACTIVATE_FAILED = 'DEACTIVATE_FAILED';

export const OPEN_NAME_BOX = 'OPEN_NAME_BOX';
export const OPEN_USERNAME_BOX = 'OPEN_USERNAME_BOX';
export const OPEN_EMAIL_BOX = 'OPEN_EMAIL_BOX';
export const OPEN_DEACTIVATE_BOX = 'OPEN_DEACTIVATE_BOX';
export const CLEAR_ACTION_BOX = 'CLEAR_ACTION_BOX';

export const SELECT_ELEMENT = 'SELECT_ELEMENT';
export const SELECT_FLOWER = 'SELECT_FLOWER';
export const SELECT_CRYSTAL = 'SELECT_CRYSTAL';