export const SET_USER_ACCESS = 'SET_USER_ACCESS';
export const SIGNUP = 'SIGNUP';
export const LOGIN = 'LOGIN';
export const MEMBER = 'MEMBER';

export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const ROUTE_HOME = 'ROUTE_HOME';
export const ROUTE_GAME = 'ROUTE_GAME';
export const ROUTE_PROFILE = 'ROUTE_PROFILE';

export const REQUEST_USER_PENDING = 'REQUEST_USER_PENDING';
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS';
export const REQUEST_USER_FAILED = 'REQUEST_USER_FAILED';

export const UPDATE_NAME = 'UPDATE_NAME';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_POTIONS = 'UPDATE_POTIONS';
export const UPDATE_USERNAME_EMAIL = 'UPDATE_USERNAME_EMAIL';